### ISSUE TITLE
Typo or bug in pee rate setup

### ISSUE THREAD

**Issue by exieln** [Noober84555/RetardsInSpaceSS13#16]
![dreamseeker_2018-03-03_10-59-26](https://user-images.githubusercontent.com/25045482/36936348-3ff51bca-1ed2-11e8-9a16-8244fe21f08b.png)
either fix the typo or edit the pee rate to include 1

**Comment by Noober84555** [comment]
SHIT!!!!!!!!!!!!!!!!

**Comment by exieln** [comment]
fixed
